### ISSUE TITLE
Add option to include other statistical summaries in the descriptive table

### ISSUE THREAD

**Issue by ashirwad** [isubirana/compareGroups#17]
Hello, 

Thanks for your package. I was trying to use the `descrTable` function to generate a descriptive summary table for my data set. By default, the function adds `Mean (SD)`  for continuous variables. I was wondering if it's currently possible to add other statistical summaries such as `range` or `max; min`, etc. along with `Mean (SD)`? If not, it would be a great addition to have in the package.

Thanks!

**Comment by isubirana** [comment]
Hi,

Thank you for using the compareGroups package.

There is the "method" argument in descrTable function to set whether to report means and standard deviation (method=1) or medians and quartiles (method=2). Also, by setting the argument Q1=0 and Q3=1 you specify minimum and maximum instead of quartiles (i.e. 25th and 75th percentiles). 

Following there is an example where you report the mean and standard deviation and also median [minimum;maximum] for the same varible, in this case age.
Note the repetition of age in the formula and the specification of "age.1" meaning the second time age is in the table.

```
library(compareGroups)

data(predimed)

descrTable(group ~ age + age + sex, predimed, 
           method=c(age.1=2), Q1=0, Q3=1, 
           extra.labels=c("Mean (SD)","Median [Min;Max]","N (%)"))
```

```
--------Summary descriptives table by 'Intervention group'---------

__________________________________________________________________________________ 
                          Control       MedDiet + Nuts   MedDiet + VOO   p.overall 
                           N=2042           N=2100           N=2182                
¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯ 
Age, Mean (SD)          67.3 (6.28)      66.7 (6.02)      67.0 (6.21)      0.003   
Age, Median [Min;Max] 67.0 [49.0;82.0] 66.0 [50.0;84.0] 67.0 [49.0;87.0]   0.003   
Sex, N (%):                                                               <0.001   
    Male                812 (39.8%)      968 (46.1%)      899 (41.2%)              
    Female              1230 (60.2%)     1132 (53.9%)     1283 (58.8%)             
¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯ 
```

I hope it helps.

Regards,

Isaac.

**Comment by ashirwad** [comment]
Neat! I think you should include this information in your vignette to help future users of your package.
