### ISSUE TITLE
output in Rshiny

### ISSUE THREAD

**Issue by antoine4ucsd** [isubirana/compareGroups#28]
thank you for your amazing package. so useful!
I am trying to output my desctable output in Rshiny
I tried in the server :
renderUI or renderDataTable or renderTable
and in the UI
uiOutput or dataTableOutput or TableOutput

none of these works... do you have any advices or reproducible example?

thank you!

**Comment by isubirana** [comment]
First of all, thanks for using the compareGroups package and your kind words.

In order to output the table in a shiny app, you need to combine htmlOutput with renderText. Doing this, the table is visualitzed in HTML format. But you need to use the export2md function.
Alternatively you can visualize the table as in console using verbatimTextOutput with render Print. If you choose this second option you don't need the export2md usage. 
Below there is a simple example of a reproducible app where the user choose between two data sets and the table is returned in both, HTML format and console format.
I hope it helps.

Regards,

Isaac.

```
library(shiny)
library(compareGroups)
data(regicor)
data(SNPs)

ui <- fluidPage(
    titlePanel("Example compareGroups"),
    sidebarLayout(
        sidebarPanel(
            selectInput("which.data", "Select data", c("regicor","SNPs"))
        ),
        mainPanel(
          tabsetPanel(
            tabPanel("HTML format",
              htmlOutput("tabHTML")
            ),
            tabPanel("console format",
              verbatimTextOutput("tabConsole")
            )
          )
        )
    )
)


server <- function(input, output) {

    output$tabHTML <- renderText({
      if (input$which.data=='regicor')
        return(export2md(descrTable(regicor)))
      if (input$which.data=='SNPs')
        return(export2md(descrTable(SNPs)))
    })
    
    output$tabConsole <- renderPrint({
      if (input$which.data=='regicor')
        return(descrTable(regicor))
      if (input$which.data=='SNPs')
        return(descrTable(SNPs))
    })
}

shinyApp(ui = ui, server = server)
```

**Comment by antoine4ucsd** [comment]
thank you for your prompt and detailed answer! that will help a lot.
