### ISSUE TITLE
"export2word" rises an warning error

### ISSUE THREAD

**Issue by xmarti6** [isubirana/compareGroups#8]
Hi, congrats for this wonderful package! I would like to report this issue when exporting to word. It happens with the example reported in help and with other data. Not sure if this is a harmless warning-error or we should be worried. The output seems ok. Could you confirm is safe?

Many thanks

```
> ?export2word
> packageVersion("compareGroups")
[1] ‘4.1.0’

> require(compareGroups)
> data(regicor)
     
# example on an ordinary table
> res <- createTable(compareGroups(year ~ . -id, regicor), hide = c(sex=1), hide.no = 'no')
> export2word(res, file = tempfile(fileext=".docx"))

Warning message:
In export2md(x, which.table, nmax, header.labels, format = "markdown") :
  error


```

**Comment by isubirana** [comment]
Thanks for your kind words, and using the compareGroups package.

You can ignore the "error" message. This occurs since the `export2word` function calls to `export2md` which prints "error" when is called outside a Rmd document file.
If you use the lattest version 4.1.1 from Github the "error" is not printed anymore.

Isaac.
